In [21]:
import time
import numpy as np
import pandas as pd
import seaborn as sns
import math
import sys
import copy
import matplotlib.pyplot as plt 
%matplotlib inline
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore') 
from zipfile import ZipFile 
import sklearn
import tensorflow as tf
from tensorflow import keras

In [30]:
data = pd.read_csv('insurance_data.csv')
data['age'] =data['age']/100
data.head()

age  affordibility  bought_insurance
0  0.22              1                 0
1  0.25              0                 0
2  0.47              1                 1
3  0.52              0                 0
4  0.46              1                 1

In [35]:
X_train ,X_test , Y_train, Y_test   = train_test_split(data[['age' , 'affordibility']] , data['bought_insurance'])
# X_train['age']=X_train['age']/100
# X_test['age']=X_test['age']/100
X_train.head()


age  affordibility
17  0.58              1
12  0.27              0
4   0.46              1
5   0.56              1
11  0.28              1

In [36]:
model   = keras.Sequential([
    keras.layers.Dense(1 ,input_shape=(2 ,) ,activation = 'sigmoid' , kernel_initializer='ones' ,bias_initializer = 'zeros' )
])
model.compile(
    optimizer='adam' , 
    loss='binary_crossentropy' ,
    metrics=['accuracy']
)

model.fit(X_train, Y_train ,epochs=5)




Epoch 1/5
1/1 [==============================] - 0s 2ms/step - loss: 0.7406 - accuracy: 0.5238
Epoch 2/5
1/1 [==============================] - 0s 1ms/step - loss: 0.7402 - accuracy: 0.5238
Epoch 3/5
1/1 [==============================] - 0s 2ms/step - loss: 0.7398 - accuracy: 0.5238
Epoch 4/5
1/1 [==============================] - 0s 3ms/step - loss: 0.7393 - accuracy: 0.5238
Epoch 5/5
1/1 [==============================] - 0s 3ms/step - loss: 0.7389 - accuracy: 0.5238


In [39]:
model.evaluate(X_test , Y_test)
coef  , intercept = model.get_weights()
coef , intercept

1/1 [==============================] - 0s 2ms/step - loss: 0.6403 - accuracy: 0.4286


(array([[0.99500155],
        [0.9950009 ]], dtype=float32),
 array([-0.00499922], dtype=float32))

In [78]:
def sigmoid(x):
    return (1/(1+math.exp(-x)))
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age +coef[1]*affordibility+intercept[0]
    return sigmoid(weighted_sum)
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
def log_loss(Y_true, Y_pred):
    epsilon  =1e-15
    Y_pred_new = [max(i,epsilon) for i in Y_pred]
    Y_pred_new = [min(1-epsilon , i) for i in Y_pred]
    Y_pred_new =np.array(Y_pred_new)
    return np.mean(Y_true*np.log(Y_pred_new) +(1-Y_true)*np.log(1-Y_pred_new))
def gradient_descent(age , affordibility , Y_true ,epochs):
    w1=w2 =1 
    bias =0 
    rate = .5
    n =len(age)
    
    for i in range(epochs):
        weighted_sum = w1*age+w2*affordibility+bias
        Y_pred = sigmoid_numpy(weighted_sum)
        logloss = log_loss(Y_true , Y_pred)
        
        w1d  = (1/n)*np.dot(np.transpose(age) , (Y_pred -Y_true))
        w2d  = (1/n)*np.dot(np.transpose(affordibility) , (Y_pred - Y_true))
        
        bias_d =np.mean(Y_pred-Y_true)
        
        w1 -=w1d*rate
        w2-=w2d*rate
        bias-=bias_d*rate
        print('epochs {} ,log loss {}  '.format(i ,logloss ))
        
    return w1,w2,bias

        
    
     


gradient_descent(X_test['age'] , X_test['affordibility'],Y_test , 100)

epochs 0 ,log loss -0.6420452745328359  
epochs 1 ,log loss -0.6051080817105208  
epochs 2 ,log loss -0.5762705632692358  
epochs 3 ,log loss -0.5537260226883632  
epochs 4 ,log loss -0.5359311256899215  
epochs 5 ,log loss -0.5216468144130101  
epochs 6 ,log loss -0.5099233532561087  
epochs 7 ,log loss -0.500057148681331  
epochs 8 ,log loss -0.49153954317622883  
epochs 9 ,log loss -0.48400895914186687  
epochs 10 ,log loss -0.4772111337526913  
epochs 11 ,log loss -0.470968297809015  
epochs 12 ,log loss -0.4651563301868852  
epochs 13 ,log loss -0.4596883225628012  
epochs 14 ,log loss -0.45450299516305875  
epochs 15 ,log loss -0.44955664649521193  
epochs 16 ,log loss -0.44481761349736  
epochs 17 ,log loss -0.4402624846267376  
epochs 18 ,log loss -0.4358735224937144  
epochs 19 ,log loss -0.4316369142072697  
epochs 20 ,log loss -0.4275415848918243  
epochs 21 ,log loss -0.4235783928905231  
epochs 22 ,log loss -0.4197395830021273  
epochs 23 ,log loss -0.416018413904796  
epo

(2.3855759285787688, 2.6470411801510223, -2.7754217070718625)

In [80]:
print(coef , intercept)

[[0.99500155]
 [0.9950009 ]] [-0.00499922]
