In [1]:
import time
import numpy as np
import pandas as pd
import seaborn as sns
import random
import math
import sys
import copy
import matplotlib.pyplot as plt 
%matplotlib inline
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore') 
from zipfile import ZipFile 
import tensorflow as tf
from tensorflow import keras



In [ ]:

tf.config.experimental.list_physical_devices()


In [21]:
from keras.datasets import cifar10
(X_train ,Y_train), (X_test , Y_test) = cifar10.load_data()
X_train =  X_train/255
X_test =  X_test/255

In [31]:
classes  = ['airplane' ,'automobile' , 'bird' , 'cat' ,'deer','dog' ,'frog' ,'horse'  ,'ship' ,'truck']
 
Y_train_categorical = keras.utils.to_categorical(
    Y_train, num_classes =10 , dtype ='float32' 
)
print(Y_train_categorical[0:5])

 
Y_test_categorical = keras.utils.to_categorical(
    Y_test, num_classes =10 , dtype ='float32' 
)
print(Y_test_categorical[0:5])

 

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [42]:
model   = keras.Sequential([
    keras.layers.Flatten(input_shape =(32,32,3)),
    keras.layers.Dense(3000 ,activation ='relu'),
    keras.layers.Dense(1000 ,activation ='relu'),
    keras.layers.Dense(10 ,activation ='sigmoid')
    
    
])

model.compile(
    optimizer='SGD' ,
    loss ='categorical_crossentropy',
    metrics=['accuracy']
)
model.fit(X_train ,Y_train_categorical, epochs=10)

Epoch 1/10
1563/1563 [==============================] - 118s 76ms/step - loss: 1.8624 - accuracy: 0.3319
Epoch 2/10
1563/1563 [==============================] - 119s 76ms/step - loss: 1.6601 - accuracy: 0.4124
Epoch 3/10
1563/1563 [==============================] - 112s 72ms/step - loss: 1.5754 - accuracy: 0.4428
Epoch 4/10
1563/1563 [==============================] - 115s 73ms/step - loss: 1.5144 - accuracy: 0.4651s - loss:
Epoch 5/10
1563/1563 [==============================] - 124s 79ms/step - loss: 1.4610 - accuracy: 0.4850
Epoch 6/10
1563/1563 [==============================] - 108s 69ms/step - loss: 1.4200 - accuracy: 0.4982
Epoch 7/10
1563/1563 [==============================] - 111s 71ms/step - loss: 1.3805 - accuracy: 0.5153
Epoch 8/10
1563/1563 [==============================] - 121s 78ms/step - loss: 1.3446 - accuracy: 0.5259
Epoch 9/10
1563/1563 [==============================] - 112s 72ms/step - loss: 1.3137 - accuracy: 0.5397
Epoch 10/10
1563/1563 [=======================

In [53]:
print(model.predict(X_test[0:1]))
print(Y_test[0])

[[3.3934712e-03 5.3261518e-03 5.8985054e-03 1.9457042e-02 1.3879538e-03
  4.1072071e-03 5.3043067e-03 2.6161546e-05 6.1205328e-03 2.8192997e-04]]
[3]
